# Generated by Django 4.2.3 on 2023-07-09 10:46

from django.db import migrations, models
import web.app_auth.validators


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='civil_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[web.app_auth.validators.validate_only_digits]),
        ),
    ]
