# Generated by Django 4.2.3 on 2023-07-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OncologyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histology_diagnose', models.TextField()),
                ('tnm', models.CharField(max_length=30)),
                ('stage', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=10)),
                ('her2', models.CharField(choices=[('plus', '+'), ('two_plus', '++'), ('three_plus', '+++')], max_length=15)),
                ('er', models.CharField(choices=[('positive', '+'), ('negative', '-')], max_length=15)),
                ('pr', models.CharField(choices=[('positive', '+'), ('negative', '-')], max_length=15)),
                ('ki_67', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.doctorprofile')),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.patientprofile')),
            ],
        ),
    ]
