# Generated by Django 4.2.3 on 2023-07-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_oncologystatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oncologystatus',
            old_name='patients',
            new_name='patient',
        ),
    ]
