# Generated by Django 4.2.3 on 2023-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_rename_patients_oncologystatus_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oncologystatus',
            options={'verbose_name': 'OncologyStatus', 'verbose_name_plural': 'OncologyStatuses'},
        ),
        migrations.AlterField(
            model_name='oncologystatus',
            name='er',
            field=models.CharField(choices=[('positive', '+'), ('negative', '-')], max_length=15, verbose_name='ER'),
        ),
        migrations.AlterField(
            model_name='oncologystatus',
            name='her2',
            field=models.CharField(choices=[('plus', '+'), ('two_plus', '++'), ('three_plus', '+++')], max_length=15, verbose_name='HER2'),
        ),
        migrations.AlterField(
            model_name='oncologystatus',
            name='ki_67',
            field=models.PositiveIntegerField(verbose_name='KI 67'),
        ),
        migrations.AlterField(
            model_name='oncologystatus',
            name='pr',
            field=models.CharField(choices=[('positive', '+'), ('negative', '-')], max_length=15, verbose_name='PR'),
        ),
        migrations.AlterField(
            model_name='oncologystatus',
            name='tnm',
            field=models.CharField(max_length=30, verbose_name='TNM'),
        ),
    ]
