# Generated by Django 4.2.3 on 2023-07-17 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_alter_oncologystatus_options_alter_oncologystatus_er_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ('user_id',), 'verbose_name': 'DoctorProfile', 'verbose_name_plural': 'DoctorProfiles'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'ordering': ('user_id',), 'verbose_name': 'PatientProfile', 'verbose_name_plural': 'PatientProfiles'},
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('for_date', models.DateField()),
                ('for_time', models.TimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.patientprofile')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
