# Generated by Django 4.2.3 on 2023-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0009_auto_20230731_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
