version: '3.4'

services:

  web:
    image: web
    build: .
    command: gunicorn --bind=0.0.0.0:8000 web.wsgi:application
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - /.env.development
    volumes:
      - /staticfiles:/app/web/web/staticfiles/
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: web_db_development
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - /staticfiles:/app/web/web/staticfiles/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web